#!/bin/sh
# env0.sh -- say what env-0 IS.
#
#   env0.sh record <out.txt>     write the manifest and print its hash
#   env0.sh check  <out.txt>     compare against sources/env0.expected, report drift
#
# WHY. The box today is `--ro-bind /usr /usr`: its contents are whatever the
# GitHub runner image happened to ship, plus whatever apt resolved that morning.
# Run 81910448983 ran on ubuntu-24.04-arm image 20260719.67.1; those rotate
# weekly. So the single largest input to every rung -- the entire userland the
# build runs in -- is undeclared and moves on its own.
#
# That is a bigger hole than anything the compiler mask closes. The mask
# subtracts three files from a distro nobody wrote down.
#
# THIS DOES NOT FIX IT. Fixing it means env-0 becomes a rootfs we build and pin,
# and the box binds that instead of the host (ARCHITECTURE.md §5a). This script
# is the step before: make the input VISIBLE and make drift NOISY, so that when
# a rung's output hash moves, "the runner image changed underneath us" is a
# question with an answer instead of a shrug.
#
# WHAT IS RECORDED. Only things that can actually reach a build: the image
# identity, the kernel the box runs under (a declared trusted input --
# TRUST-BOUNDARY.md -- but one that differs between Actions, QEMU and metal),
# and the exact version of every package named in the borrow list. Not the whole
# dpkg database: most of a runner image is never bound into anything, and a
# manifest that changes for irrelevant reasons is a manifest people learn to
# ignore.
set -eu

# The borrow list, and this is the SAME list bind-list.txt declares. If a rung
# starts needing something not named here, it should be added deliberately --
# that is a deletion-from-the-hole going the wrong way and it should be visible.
BORROWED="bash binutils bison bzip2 coreutils curl dash diffutils file findutils
flex gawk grep gzip m4 make patch perl-base python3-minimal sed tar texinfo
xz-utils bubblewrap libc6 libc-bin cpio kmod qemu-system-arm"

case "${1:?env0.sh: subcommand required}" in

  record)
    out="${2:?env0.sh record: output path required}"
    {
      echo "# env-0 manifest -- what the box starts from."
      echo "# Generated by spikes/stage4/chain/env0.sh; see ARCHITECTURE.md §5a."
      echo
      echo "image_os        ${ImageOS:-unknown}"
      echo "image_version   ${ImageVersion:-unknown}"
      echo "runner_arch     $(uname -m)"
      # THE KERNEL IS THE INPUT MOST LIKELY TO DIFFER BETWEEN ENTRY PATHS.
      # Actions gives you Azure's kernel, QEMU gives you the one you booted,
      # metal gives you the one on the disk. It is trusted by declaration in
      # every case -- but "trusted" is not "identical", and if a rung's output
      # ever diverges between Actions and QEMU this is the first line to read.
      echo "kernel          $(uname -r)"
      echo "libc            $(ldd --version 2>/dev/null | head -1 || echo unknown)"
      echo
      echo "# borrowed packages, exact versions"
      for p in $BORROWED; do
        # dpkg-query exits 0 with EMPTY output for a package it knows about
        # but that is not installed, so the || branch never fires. An empty
        # version silently reads as "recorded" in a manifest whose whole job is
        # to say what is present.
        v=$(dpkg-query -W -f='${Version}' "$p" 2>/dev/null || true)
        [ -n "$v" ] || v='<absent>'
        printf '%-22s %s\n' "$p" "$v"
      done
    } > "$out"
    # The hash covers the package versions and the image identity, NOT the
    # kernel line -- the kernel legitimately differs between entry paths and
    # including it would make the Actions/QEMU equivalence test fail for the
    # one reason the design already accepts. It is recorded, just not hashed.
    h=$(grep -v '^kernel ' "$out" | sha256sum | cut -d' ' -f1)
    echo "env0_hash       $h" >> "$out"
    echo "$h"
    ;;

  check)
    out="${2:?env0.sh check: manifest path required}"
    exp="${REPO:-$PWD}/sources/env0.expected"
    got=$(grep '^env0_hash' "$out" | awk '{print $2}')
    echo "  env-0: $got"
    sed -n '4,8p' "$out" | sed 's/^/    /'
    if [ ! -f "$exp" ]; then
      echo "    no sources/env0.expected yet -- recording this as the first observation"
      echo "    (add the hash above to pin it; drift then becomes a reported finding)"
      exit 0
    fi
    want=$(cat "$exp")
    if [ "$want" = "$got" ]; then
      echo "    matches sources/env0.expected"
    else
      # NOT A HARD FAILURE, DELIBERATELY. GitHub rotates its images weekly and
      # a red build every Tuesday teaches people to ignore the check. It is a
      # loud, recorded finding that lands in the chain record, so that when two
      # runs of the same commit produce different output hashes the reason is
      # already on the page.
      echo "    DRIFT: sources/env0.expected says $want"
      echo "    The userland every rung builds in is not the one that was pinned."
      echo "    diff the manifest against the last run's artifact before trusting"
      echo "    any output-hash comparison across the two."
    fi
    ;;

  *) echo "env0.sh: unknown subcommand $1" >&2; exit 2 ;;
esac
