#include "settings.h"

#include <glib/gstdio.h>

#define GROUP "browser"

static char *settingsPath(void)
{
    /* g_get_user_config_dir() RATHER THAN A LITERAL ~/.config, because it
     * honours XDG_CONFIG_HOME. The console shell sets that up and a session
     * that moved it would otherwise write somewhere nothing reads. */
    return g_build_filename(g_get_user_config_dir(), "veron", "browser.conf", NULL);
}

/* ONE HELPER FOR EVERY KEY, so a missing key and a malformed key take the same
 * path. g_key_file_get_boolean sets an error for both and returns FALSE, and
 * FALSE is a legitimate value here -- reading it as "the user disabled this"
 * would turn a typo in the file into a silently disabled browser. */
static gboolean readBool(GKeyFile *kf, const char *key, gboolean fallback)
{
    GError *err = NULL;
    gboolean v = g_key_file_get_boolean(kf, GROUP, key, &err);
    if (err) {
        g_error_free(err);
        return fallback;
    }
    return v;
}

void veron_settings_load(VeronSettings *s)
{
    /* THE DEFAULTS ARE SET FIRST AND UNCONDITIONALLY, so every path out of
     * this function leaves a fully populated struct. An early return on a
     * missing file used to be the kind of thing that left one field holding
     * whatever was on the stack. */
    s->persistent   = FALSE;
    s->javascript   = TRUE;
    s->localStorage = TRUE;
    s->cookies      = TRUE;
    s->downloads    = TRUE;

    char *path = settingsPath();
    GKeyFile *kf = g_key_file_new();
    if (g_key_file_load_from_file(kf, path, G_KEY_FILE_NONE, NULL)) {
        s->persistent   = readBool(kf, "persistent",    FALSE);
        s->javascript   = readBool(kf, "javascript",    TRUE);
        s->localStorage = readBool(kf, "local-storage", TRUE);
        s->cookies      = readBool(kf, "cookies",       TRUE);
        s->downloads    = readBool(kf, "downloads",     TRUE);
    }
    g_key_file_free(kf);
    g_free(path);
}

gboolean veron_settings_save(const VeronSettings *s)
{
    char *path = settingsPath();
    char *dir  = g_path_get_dirname(path);

    /* THE DIRECTORY MAY NOT EXIST ON A FIRST RUN and g_file_set_contents does
     * not create one, which is how a save can fail on a machine where
     * everything else is fine. */
    gboolean ok = (g_mkdir_with_parents(dir, 0700) == 0);

    if (ok) {
        GKeyFile *kf = g_key_file_new();
        g_key_file_set_boolean(kf, GROUP, "persistent",    s->persistent);
        g_key_file_set_boolean(kf, GROUP, "javascript",    s->javascript);
        g_key_file_set_boolean(kf, GROUP, "local-storage", s->localStorage);
        g_key_file_set_boolean(kf, GROUP, "cookies",       s->cookies);
        g_key_file_set_boolean(kf, GROUP, "downloads",     s->downloads);

        gsize len = 0;
        char *data = g_key_file_to_data(kf, &len, NULL);
        GError *err = NULL;
        ok = g_file_set_contents(path, data, (gssize)len, &err);
        if (!ok) {
            g_warning("veron-settings: cannot write %s: %s", path,
                      err ? err->message : "unknown");
            g_clear_error(&err);
        }
        g_free(data);
        g_key_file_free(kf);
    } else {
        g_warning("veron-settings: cannot create %s", dir);
    }

    g_free(dir);
    g_free(path);
    return ok;
}

gboolean veron_settings_set(VeronSettings *s, const char *key, gboolean value)
{
    gboolean *field = NULL;

    if (!g_strcmp0(key, "persistent"))         field = &s->persistent;
    else if (!g_strcmp0(key, "javascript"))    field = &s->javascript;
    else if (!g_strcmp0(key, "local-storage")) field = &s->localStorage;
    else if (!g_strcmp0(key, "cookies"))       field = &s->cookies;
    else if (!g_strcmp0(key, "downloads"))     field = &s->downloads;

    if (!field || *field == value)
        return FALSE;

    *field = value;
    return TRUE;
}

/* ---- the page -------------------------------------------------------- */

/* ONE ROW. The link always names the OPPOSITE of the current value, so the
 * control is idempotent under a reload: refreshing the settings page re-issues
 * a GET for the page itself, never for a toggle, because the toggle URL is the
 * thing that was navigated away from rather than the thing that was landed on.
 *
 * THE STATE IS IN THE TEXT, NOT ONLY IN A COLOUR. "On"/"Off" is readable when
 * the styling fails to load, which for a page generated by the browser it is
 * about to be rendered in is not a hypothetical. */
static void appendRow(GString *out, const char *key, const char *title,
                      const char *detail, gboolean on)
{
    char *esc_title  = g_markup_escape_text(title, -1);
    char *esc_detail = g_markup_escape_text(detail, -1);

    g_string_append_printf(out,
        "<div class=row>"
          "<div class=text><div class=title>%s</div><div class=detail>%s</div></div>"
          "<a class=\"toggle %s\" href=\"%s:settings?set=%s&amp;value=%d\">%s</a>"
        "</div>\n",
        esc_title, esc_detail,
        on ? "on" : "off",
        VERON_SCHEME, key, on ? 0 : 1,
        on ? "On" : "Off");

    g_free(esc_title);
    g_free(esc_detail);
}

char *veron_settings_html(const VeronSettings *s)
{
    GString *out = g_string_new(NULL);

    g_string_append(out,
        "<!DOCTYPE html>\n<html><head><meta charset=\"utf-8\">"
        "<title>Settings</title><style>"
        "body{font:14px sans-serif;margin:0;background:#f4f4f6;color:#111}"
        ".wrap{max-width:640px;margin:32px auto;padding:0 16px}"
        "h1{font-size:22px;font-weight:600;margin:0 0 4px}"
        ".sub{color:#666;margin:0 0 24px}"
        ".row{display:flex;align-items:center;justify-content:space-between;"
             "gap:16px;background:#fff;border:1px solid #e0e0e4;"
             "border-radius:8px;padding:14px 16px;margin-bottom:10px}"
        ".title{font-weight:600}"
        ".detail{color:#666;font-size:13px;margin-top:2px}"
        ".toggle{flex:none;min-width:52px;text-align:center;text-decoration:none;"
                "padding:6px 14px;border-radius:999px;font-weight:600;"
                "border:1px solid transparent}"
        ".toggle.on{background:#2f7fd9;color:#fff}"
        ".toggle.off{background:#e6e6ea;color:#555;border-color:#d0d0d6}"
        ".note{color:#666;font-size:13px;margin-top:20px;line-height:1.5}"
        "</style></head><body><div class=wrap>"
        "<h1>Settings</h1>"
        "<p class=sub>Saved to your home directory and kept across reboots.</p>\n");

    appendRow(out, "persistent", "Keep history and sign-ins",
              "Save cookies, cache and site data to disk so you stay signed in "
              "after closing the browser. Off means every session starts clean.",
              s->persistent);
    appendRow(out, "javascript", "JavaScript",
              "Run scripts on pages. Turning this off breaks many sites.",
              s->javascript);
    appendRow(out, "cookies", "Cookies",
              "Let sites store a cookie. Off means you cannot stay signed in.",
              s->cookies);
    appendRow(out, "local-storage", "Local storage",
              "Let sites keep data in the browser between page loads.",
              s->localStorage);
    appendRow(out, "downloads", "Downloads",
              "Allow saving files, and show the downloads button in the toolbar.",
              s->downloads);

    /* WHAT NEEDS A RELOAD AND WHAT DOES NOT IS STATED, because a setting that
     * appears to do nothing is worse than one that says when it takes effect.
     * JavaScript and local storage are read by the page as it loads; the
     * cookie policy and the downloads switch apply immediately. */
    g_string_append(out,
        "<p class=note>JavaScript and local storage take effect the next time a "
        "page loads &mdash; reload the page you want them to apply to. "
        "Cookies and downloads apply straight away. "
        "<b>Keeping history and sign-ins takes effect when you next start the "
        "browser</b> &mdash; the session is chosen before the first page loads "
        "and cannot change while it is running."
        "</p></div></body></html>\n");

    return g_string_free(out, FALSE);
}
