/* setjmp/longjmp for code generated by tcc, in tcc's own assembler syntax.
 *
 * WHY THIS EXISTS BESIDE setjmp-aarch64.c. That file is written in M2libc's
 * M1 MACRO vocabulary -- `mov_x0,x1` -- which micro-c emits and a real
 * assembler has never heard of:
 *
 *     setjmp-aarch64.c:62: error: unrecognized opcode mov_x0
 *
 * and it deliberately saves only what MICRO-C's calling convention uses (x13,
 * x17, x18, lr), which its own header says is "sufficient for code this
 * compiler generates" and "wrong against any other compiler". gen2 is compiled
 * by mc-tcc, which is a real tcc emitting ordinary AAPCS code, so it needs the
 * ordinary AAPCS registers saved and the ordinary syntax to say so.
 *
 * WHAT AAPCS REQUIRES A setjmp TO PRESERVE:
 *
 *     x19-x28   callee-saved general registers
 *     x29       frame pointer
 *     x30       link register -- where longjmp returns to
 *     sp        stack pointer
 *     d8-d15    callee-saved floating-point registers
 *
 * THE FLOATING-POINT HALF IS SAVED AND IS NOT TRUSTWORTHY HERE, which is worth
 * stating rather than leaving to be discovered. micro-c maps float, double and
 * long double to one word-sized integer, so the tcc it builds does not put
 * anything meaningful in d8-d15 in the first place. Saving them costs eight
 * instructions and makes this file correct for a compiler that does; not
 * saving them would make it quietly wrong for one. The cost is the honest
 * side of that trade.
 *
 * jmp_buf IS long[32] -- 256 bytes, from micro-c-libc/setjmp.h. The layout
 * below uses 168 of them and the rest are spare. It has to agree with that
 * typedef and with nothing else: nothing outside this pair reads a jmp_buf.
 *
 *     0    x19, x20            80   x29, x30
 *     16   x21, x22            96   sp
 *     32   x23, x24            104  d8,  d9
 *     48   x25, x26            120  d10, d11
 *     64   x27, x28            136  d12, d13
 *                              152  d14, d15
 *
 * setjmp RETURNS 0 THE FIRST TIME and whatever longjmp passed the second.
 * C requires longjmp(env, 0) to arrive as 1, because 0 is how the caller tells
 * the two apart -- so the value is forced to 1 when it is zero. tcc relies on
 * this: libtcc.c wraps every compilation in setjmp and tcc_error longjmps out
 * with a non-zero code, but a zero would silently look like a fresh call and
 * re-enter the compile.
 */

__asm__(
".global setjmp\n"
".global _setjmp\n"
"setjmp:\n"
"_setjmp:\n"
"    stp x19, x20, [x0, #0]\n"
"    stp x21, x22, [x0, #16]\n"
"    stp x23, x24, [x0, #32]\n"
"    stp x25, x26, [x0, #48]\n"
"    stp x27, x28, [x0, #64]\n"
"    stp x29, x30, [x0, #80]\n"
"    mov x1, sp\n"
"    str x1, [x0, #96]\n"
"    stp d8,  d9,  [x0, #104]\n"
"    stp d10, d11, [x0, #120]\n"
"    stp d12, d13, [x0, #136]\n"
"    stp d14, d15, [x0, #152]\n"
"    mov x0, #0\n"
"    ret\n"
);

__asm__(
".global longjmp\n"
".global _longjmp\n"
"longjmp:\n"
"_longjmp:\n"
"    ldp x19, x20, [x0, #0]\n"
"    ldp x21, x22, [x0, #16]\n"
"    ldp x23, x24, [x0, #32]\n"
"    ldp x25, x26, [x0, #48]\n"
"    ldp x27, x28, [x0, #64]\n"
"    ldp x29, x30, [x0, #80]\n"
"    ldr x2, [x0, #96]\n"
"    mov sp, x2\n"
"    ldp d8,  d9,  [x0, #104]\n"
"    ldp d10, d11, [x0, #120]\n"
"    ldp d12, d13, [x0, #136]\n"
"    ldp d14, d15, [x0, #152]\n"
/* THE RETURNED VALUE: val, or 1 if val was 0.
 *
 * `cbnz` rather than `cmp` + `bne`, and not because it is shorter. tcc's arm64
 * assembler -- the one patches/tcc-arm64-asm/ adds -- does not know the
 * `bne` spelling at all:
 *
 *     error: unrecognized opcode bne
 *
 * It accepts `b.ne`, and it accepts cbnz/cbz/csinc; it does not accept csel.
 * The vocabulary is narrower than the instruction set, which is the same
 * lesson M2libc's macro set taught four times over in this series -- correct
 * aarch64 is not the same thing as assemblable aarch64. Probed before writing
 * rather than after failing. */
"    mov x0, x1\n"
"    cbnz x0, 1f\n"
"    mov x0, #1\n"
"1:\n"
"    ret\n"
);
