#!/usr/bin/env python3
"""c2str.py -- tinycc's conftest.c -DC2STR, ported line for line.

tcc with CONFIG_TCC_PREDEFS bakes include/tccdefs.h into the compiler as C
strings; upstream generates tccdefs_.h by compiling this converter with the
HOST C compiler and running it. The zero-budget chain has no host compiler,
and the old base (the toolbox tarball) carried a tccdefs_.h a GitHub runner's
gcc had produced -- a generated input nobody could regenerate here. This is
the same algorithm without the compiler: read tinycc's conftest.c (the
#if C2STR half) beside it; the structure and names are kept so the two can
be compared function by function.

    python3 tools/c2str.py include/tccdefs.h tccdefs_.h

VERIFIED (2026-08-25): on include/tccdefs.h at pin 5ec0e6f8 this produces
the toolbox tarball's gcc-built tccdefs_.h byte for byte (13286 bytes).
"""
import sys

PLATFORM_MACROS = [
    ("__i386__", "TCC_TARGET_I386"),
    ("__x86_64__", "TCC_TARGET_X86_64"),
    ("_WIN32", "TCC_TARGET_PE"),
    ("__arm__", "TCC_TARGET_ARM"),
    ("__ARM_EABI__", "TCC_ARM_EABI"),
    ("__aarch64__", "TCC_TARGET_ARM64"),
    ("__riscv", "TCC_TARGET_RISCV64"),
    ("__APPLE__", "TCC_TARGET_MACHO"),
    ("__FreeBSD__", "TARGETOS_FreeBSD"),
    ("__FreeBSD_kernel__", "TARGETOS_FreeBSD_kernel"),
    ("__OpenBSD__", "TARGETOS_OpenBSD"),
    ("__NetBSD__", "TARGETOS_NetBSD"),
    ("__linux__", "TARGETOS_Linux"),
    ("__ANDROID__", "TARGETOS_ANDROID"),
    ("__SIZEOF_POINTER__", "PTR_SIZE"),
    ("__SIZEOF_LONG__", "LONG_SIZE"),
]

def isid(c):
    return c.isascii() and (c.isalnum() or c == "_")

def isspc(c):
    return ord(c) <= 0x20 and c != "\0"

def convert(src, dst):
    lines = open(src, "r", encoding="latin-1").read().split("\n")
    # fgets semantics: the last element after split is "" when the file ends
    # with a newline; drop it so the loop sees exactly the file's lines.
    if lines and lines[-1] == "":
        lines.pop()
    out = []
    cmt = 0
    cmt_n = 0
    i = 0
    while i < len(lines):
        # read a logical line: strip trailing whitespace, join continuations
        l = lines[i].rstrip(" \t\r\n\f\v"); i += 1
        while l.endswith("\\"):
            l = l[:-1] + " "
            nxt = lines[i].rstrip(" \t\r\n\f\v") if i < len(lines) else ""
            if i < len(lines):
                i += 1
            l = l + nxt
            l = l.rstrip(" \t\r\n\f\v")
        # count & skip leading spaces
        f = 0
        while f < len(l) and isspc(l[f]):
            f += 1
        p = l[f:]
        # comments
        if cmt == 0 and p.startswith("/"):
            if p[1:2] == "*":
                cmt = 2
            if p[1:2] == "/":
                cmt = 1
        if cmt:
            s = l
            cmt_n += 1
            if cmt_n == 1:
                s += " (converted, do not edit this file)"
            out.append(s + "\n")
            if cmt == 1:
                cmt = 0
            if cmt == 2 and len(l) >= 2 and l.endswith("*/"):
                cmt = 0
            continue
        if f < 4:
            # replace machine/os macros by compile-time counterparts, output as is
            q = []
            j = 0
            while True:
                matched = False
                for r, rep in PLATFORM_MACROS:
                    if p.startswith(r, j):
                        j += len(r)
                        q.append(rep)
                        matched = True
                        break
                if matched:
                    continue
                if j >= len(p):
                    break
                q.append(p[j]); j += 1
            out.append("".join(q) + "\n")
            continue
        # quoted output with whitespace squeezed, trailing comment kept outside
        q = []
        s = 0; e = 0; f2 = 0
        j = 0
        p0 = 0
        while True:
            c = p[j] if j < len(p) else "\0"; j += 1
            if c != "\0" and isspc(c):
                s = 1
                continue
            if c == "/" and (p[j:j+1] == "/" or p[j:j+1] == "*"):
                c = "\0"
            elif s and q and ((isid(q[-1]) and isid(c))
                              or (len(q) >= 2 and q[0] == "#" and q[1] == "d" and f2 < 2 and not e)):
                q.append(" "); f2 += 1
            s = 0
            if c == "(":
                e += 1
            if c == ")":
                e -= 1
            if c == "\\" or c == '"':
                q.append("\\")
            if c == "\0":
                break
            q.append(c)
            p0 = j
        rest = p[p0:]
        out.append('    "' + "".join(q) + '\\n"' + rest + "\n")
    with open(dst, "w", encoding="latin-1", newline="") as fp:
        fp.write("".join(out))

if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit("usage: c2str.py include/tccdefs.h tccdefs_.h")
    convert(sys.argv[1], sys.argv[2])
