#!/usr/bin/env python3
# tools/img-compare.py -- COMPARE TWO ext4 IMAGES ENTRY BY ENTRY.
#
# WHY THIS EXISTS. files.tsv is generated by walking dest/ -- the per-package
# DESTDIRs -- and it skips build_only packages by design. The image is
# sysroot/, which is the stage-4 sysroot with packages merged on top. So
# files.tsv cannot see anything the sysroot brought and no package installed:
# measured on the 2026-08-31 amd64 image, it lists 15,634 of 34,383 entries.
# The 18,749 it misses include usr/lib (10,171), usr/share (5,482),
# usr/include (3,526) and usr/bin (562).
#
# That matters when two images disagree. `diff files.tsv files.tsv` came back
# with a single line while IMAGE-SHA256 differed, and a reader could take that
# as "one difference". It is one difference AMONG THE 45% files.tsv CAN SEE.
# This walks the filesystems themselves, so absence of a difference means
# absence.
#
# TWO MODES, AND THE CHEAP ONE FIRST.
#
#   meta   every entry's type, mode, size, symlink target, hardlink grouping.
#          Reads directory blocks only -- no extraction, no temp space, runs
#          in seconds on a 1.7 GB image. Catches a missing path, a changed
#          mode, a retargeted symlink, a resized file.
#   full   additionally sha256s every regular file, which requires dumping
#          each one. Needs roughly the image's content size in scratch and
#          takes minutes. Only worth running when `meta` comes back clean and
#          the images still differ -- that is the case where the difference
#          is INSIDE a file whose size did not change.
#
# Run meta first. If it names the difference, full has nothing to add.
#
#   usage:
#     img-compare.py meta A.img B.img
#     img-compare.py full A.img B.img SCRATCHDIR
#
# debugfs comes from e2fsprogs; veron-tools/debugfs is the one the build
# already trusts. Set DEBUGFS=/path/to/debugfs to choose another.
import hashlib
import os
import re
import shutil
import subprocess
import sys

DEBUGFS = os.environ.get("DEBUGFS", "debugfs")

# debugfs `ls -l` line:  inode  mode (type)  uid  gid  size  date  name
# The mode is OCTAL and printed without a prefix. Parsing it as decimal is a
# silent, total failure -- every directory reads as a regular file, the walk
# never recurses, and the tool reports a handful of root entries as the whole
# image. int(mode, 8) or nothing.
LINE = re.compile(r"^\s*(\d+)\s+(\d+)\s+\(\d+\)\s+(\d+)\s+(\d+)\s+(\d+)\s+\S+\s+\S+\s+(.*)$")


def run_ls(img, paths):
    cmds = "".join("ls -l %s\n" % p for p in paths)
    p = subprocess.run([DEBUGFS, "-f", "/dev/stdin", img],
                       input=cmds, capture_output=True, text=True)
    return p.stdout


def walk(img):
    """Every entry in the image, keyed by path without a leading slash.

    BREADTH FIRST AND BATCHED. One debugfs invocation per directory would be
    ~2,400 process spawns; feeding a level's worth of `ls -l` commands through
    -f does the same work in a handful.
    """
    entries, inodes = {}, {}
    level, seen = ["/"], set()
    while level:
        out = run_ls(img, level)
        cur, nxt = None, []
        for ln in out.split("\n"):
            s = ln.strip()
            if s.startswith("debugfs:") and "ls -l" in s:
                cur = s.split("ls -l", 1)[1].strip()
                continue
            m = LINE.match(ln)
            if not m or cur is None:
                continue
            ino, mode, uid, gid, size, name = m.groups()
            if name in (".", ".."):
                continue
            mode = int(mode, 8)
            path = (cur.rstrip("/") + "/" + name).lstrip("/")
            kind = {0o100000: "f", 0o040000: "d", 0o120000: "l"}.get(
                mode & 0o170000, "?")
            entries[path] = {
                "kind": kind, "mode": "%04o" % (mode & 0o7777),
                "size": int(size), "ino": int(ino),
                "uid": int(uid), "gid": int(gid),
            }
            if kind == "d":
                if path not in seen:
                    seen.add(path)
                    nxt.append("/" + path)
            elif kind == "f":
                inodes.setdefault(int(ino), []).append(path)
        level = nxt

    # SYMLINK TARGETS. A link's target IS its content -- repoint /bin and you
    # have a different system with identical metadata everywhere else. Fast
    # symlinks store the target in the inode, so `stat` prints it.
    links = [p for p, e in entries.items() if e["kind"] == "l"]
    for i in range(0, len(links), 200):
        chunk = links[i:i + 200]
        out = run_ls(img, [])  # placeholder to keep one code path
        cmds = "".join('stat /%s\n' % p for p in chunk)
        p = subprocess.run([DEBUGFS, "-f", "/dev/stdin", img],
                           input=cmds, capture_output=True, text=True)
        cur = None
        for ln in p.stdout.split("\n"):
            s = ln.strip()
            if s.startswith("debugfs:") and "stat /" in s:
                cur = s.split("stat /", 1)[1].strip()
                continue
            m = re.search(r"Fast link dest:\s*\"(.*)\"", ln)
            if m and cur in entries:
                entries[cur]["target"] = m.group(1)

    # HARDLINK GROUPS, resolved after the walk and named by their
    # lexicographically first member so walk order cannot change the answer.
    # Whether two paths are one inode or two copies changes the image even
    # when every byte of content matches.
    for ino, paths in inodes.items():
        if len(paths) > 1:
            primary = sorted(paths)[0]
            for p in paths:
                entries[p]["link_group"] = primary
    return entries


def sha_of(img, path, scratch):
    tmp = os.path.join(scratch, "_dump")
    subprocess.run([DEBUGFS, "-R", 'dump /%s %s' % (path, tmp), img],
                   capture_output=True, text=True)
    if not os.path.exists(tmp):
        return "UNREADABLE"
    h = hashlib.sha256()
    with open(tmp, "rb") as f:
        for c in iter(lambda: f.read(1 << 20), b""):
            h.update(c)
    os.unlink(tmp)
    return h.hexdigest()


def compare(a, b, mode, scratch=None):
    print("walking A: %s" % a); ea = walk(a)
    print("walking B: %s" % b); eb = walk(b)
    print("  A entries: %d" % len(ea))
    print("  B entries: %d" % len(eb))

    problems = []
    for p in sorted(set(ea) | set(eb)):
        x, y = ea.get(p), eb.get(p)
        if x is None:
            problems.append(("B-ONLY", p, "absent", "%s mode %s" % (y["kind"], y["mode"]))); continue
        if y is None:
            problems.append(("A-ONLY", p, "%s mode %s" % (x["kind"], x["mode"]), "absent")); continue
        if x["kind"] != y["kind"]:
            problems.append(("TYPE", p, x["kind"], y["kind"])); continue
        if x["mode"] != y["mode"]:
            problems.append(("MODE", p, x["mode"], y["mode"]))
        if (x["uid"], x["gid"]) != (y["uid"], y["gid"]):
            problems.append(("OWNER", p, "%d:%d" % (x["uid"], x["gid"]),
                             "%d:%d" % (y["uid"], y["gid"])))
        if x["kind"] == "f" and x["size"] != y["size"]:
            problems.append(("SIZE", p, str(x["size"]), str(y["size"])))
        if x["kind"] == "l" and x.get("target") != y.get("target"):
            problems.append(("SYMLINK-TARGET", p, x.get("target"), y.get("target")))
        if x.get("link_group") != y.get("link_group"):
            problems.append(("HARDLINK-GROUP", p,
                             x.get("link_group", "-"), y.get("link_group", "-")))

    if mode == "full":
        # ONLY THE FILES metadata COULD NOT SEPARATE. Same size in both is
        # exactly the case where content can still differ and nothing above
        # would notice.
        same_size = [p for p in sorted(set(ea) & set(eb))
                     if ea[p]["kind"] == "f" and ea[p]["size"] == eb[p]["size"]]
        print("  hashing %d same-size regular files..." % len(same_size))
        for n, p in enumerate(same_size, 1):
            if n % 2000 == 0:
                print("    %d/%d" % (n, len(same_size)))
            ha, hb = sha_of(a, p, scratch), sha_of(b, p, scratch)
            if ha != hb:
                problems.append(("CONTENT", p, ha[:16], hb[:16]))

    print()
    if not problems:
        print("IDENTICAL -- every entry matches%s." %
              ("" if mode == "full" else " (metadata only; run `full` for content)"))
        return 0
    kinds = {}
    for k, p, x, y in problems:
        kinds.setdefault(k, []).append((p, x, y))
    print("NOT IDENTICAL -- %d difference(s)" % len(problems))
    for k in sorted(kinds):
        rows = kinds[k]
        print("\n%s (%d)" % (k, len(rows)))
        for p, x, y in sorted(rows):
            print("  %s" % p)
            print("      A: %s" % x)
            print("      B: %s" % y)
    return 1


if __name__ == "__main__":
    if len(sys.argv) < 4 or sys.argv[1] not in ("meta", "full"):
        sys.stderr.write(
            "usage:\n"
            "  img-compare.py meta A.img B.img\n"
            "  img-compare.py full A.img B.img SCRATCHDIR\n")
        raise SystemExit(2)
    if not shutil.which(DEBUGFS) and not os.path.exists(DEBUGFS):
        sys.stderr.write("debugfs not found -- set DEBUGFS=veron-tools/debugfs\n")
        raise SystemExit(2)
    m, A, B = sys.argv[1], sys.argv[2], sys.argv[3]
    sc = sys.argv[4] if len(sys.argv) > 4 else "/var/tmp"
    if m == "full":
        os.makedirs(sc, exist_ok=True)
    raise SystemExit(compare(A, B, m, sc))
