#!/usr/bin/env python3
# tools/img-compare.py -- COMPARE TWO ext4 IMAGES. EVERY ENTRY, EVERY FIELD.
#
# WHY THIS EXISTS. files.tsv is generated by walking dest/ -- the per-package
# DESTDIRs -- and it skips build_only packages by design. The image is
# sysroot/. Measured on the 2026-08-31 amd64 pair, files.tsv listed 15,634 of
# the image's 34,383 entries; the 18,749 it could not see included usr/lib
# (10,171), usr/share (5,482), usr/include (3,526) and usr/bin (562). A one-
# line files.tsv diff sat beside a differing IMAGE-SHA256 and read as "one
# difference". It was one difference among the 45% files.tsv can see.
#
# THIS HASHES EVERY REGULAR FILE IN BOTH IMAGES. An earlier version compared
# metadata only and hashed nothing, reasoning that a size change is already
# reported as SIZE. That reasoning cost hours: /usr/bin/libtool,
# /usr/bin/perlbug and /usr/bin/perlthanks differ in CONTENT at IDENTICAL
# SIZE, so the metadata pass reported them as matching, and they surfaced only
# by accident in a records file that happens to store hashes. A tool that
# prints "identical" while three files differ is worse than no tool.
#
# So: no sampling, no size shortcut, no category the tool decides not to look
# at. Content, size, mode, owner, type, symlink target, hardlink grouping,
# presence and absence, for every entry in either image. A path that differs
# in two ways is reported under both, because deciding which difference is
# "the real cause" is the reader's judgement and not this program's.
#
# COST. One dump and one hash per file, batched through debugfs so it is a few
# hundred processes rather than 60,000. On a 1.7 GB image with ~30,000 files
# expect several minutes. Peak scratch is ONE BATCH, not the whole image:
# dumps are hashed and unlinked as they go.
#
#   usage:
#     img-compare.py A.img B.img [--scratch DIR] [--batch N] [--quick]
#
#   --quick   metadata only. No dumping, no hashing. Triage only -- it CANNOT
#             see a same-size content change, and it says so in its own output
#             rather than letting a clean run be mistaken for a match.
#
# debugfs comes from e2fsprogs; veron-tools/debugfs is the one the build
# already trusts. Set DEBUGFS=/path/to/debugfs to choose another.
import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile

def find_debugfs():
    """veron-tools/debugfs first, then the host's.

    THE TOOL FINDS ITS OWN debugfs. Requiring DEBUGFS=veron-tools/debugfs on
    every invocation is work the script can do and the reader cannot forget:
    the bundle sits at a known place relative to the repo root, the build
    already trusts that binary over the host's, and a comparison run with the
    wrong one is a comparison nobody should trust. $DEBUGFS still wins if it
    is set, for the case where neither of those is the right answer.
    """
    if os.environ.get("DEBUGFS"):
        return os.environ["DEBUGFS"]
    here = os.path.dirname(os.path.abspath(__file__))
    for c in (os.path.join(here, os.pardir, "veron-tools", "debugfs"),
              os.path.join(os.getcwd(), "veron-tools", "debugfs")):
        if os.path.exists(c):
            return os.path.abspath(c)
    return shutil.which("debugfs") or "debugfs"


DEBUGFS = None

# debugfs `ls -l`:  inode  mode (type)  uid  gid  size  date  name
# THE MODE IS OCTAL AND PRINTED WITHOUT A PREFIX. Parsing it as decimal is a
# silent, total failure: every directory reads as a regular file, the walk
# never recurses, and the tool reports the root directory as the whole image.
# int(mode, 8) or nothing.
LINE = re.compile(r"^\s*(\d+)\s+(\d+)\s+\(\d+\)\s+(\d+)\s+(\d+)\s+(\d+)\s+\S+\s+\S+\s+(.*)$")


def debugfs_batch(img, commands):
    p = subprocess.run([DEBUGFS, "-f", "/dev/stdin", img],
                       input="".join(commands), capture_output=True, text=True)
    return p.stdout


def walk(img):
    """Every entry in the image, keyed by path with no leading slash."""
    entries, inodes = {}, {}
    level, seen = ["/"], set()
    while level:
        out = debugfs_batch(img, ["ls -l %s\n" % p for p in level])
        cur, nxt = None, []
        for ln in out.split("\n"):
            s = ln.strip()
            if s.startswith("debugfs:") and "ls -l" in s:
                cur = s.split("ls -l", 1)[1].strip()
                continue
            m = LINE.match(ln)
            if not m or cur is None:
                continue
            ino, mode, uid, gid, size, name = m.groups()
            if name in (".", ".."):
                continue
            mode = int(mode, 8)
            path = (cur.rstrip("/") + "/" + name).lstrip("/")
            kind = {0o100000: "f", 0o040000: "d", 0o120000: "l"}.get(
                mode & 0o170000, "?")
            entries[path] = {"kind": kind, "mode": "%04o" % (mode & 0o7777),
                             "size": int(size), "uid": int(uid), "gid": int(gid)}
            if kind == "d":
                if path not in seen:
                    seen.add(path)
                    nxt.append("/" + path)
            elif kind == "f":
                inodes.setdefault(int(ino), []).append(path)
        level = nxt

    # SYMLINK TARGETS. A link's target IS its content. Repoint /bin and you
    # have a different system with identical metadata everywhere else.
    links = [p for p, e in entries.items() if e["kind"] == "l"]
    for i in range(0, len(links), 200):
        out = debugfs_batch(img, ['stat /%s\n' % p for p in links[i:i + 200]])
        cur = None
        for ln in out.split("\n"):
            s = ln.strip()
            if s.startswith("debugfs:") and "stat /" in s:
                cur = s.split("stat /", 1)[1].strip()
                continue
            m = re.search(r'Fast link dest:\s*"(.*)"', ln)
            if m and cur in entries:
                entries[cur]["target"] = m.group(1)
    for e in entries.values():
        if e["kind"] == "l":
            e.setdefault("target", "<slow-link-unread>")

    # HARDLINK GROUPS, named by the lexicographically first member so walk
    # order cannot change the answer. Whether two paths are one inode or two
    # copies changes the image even when every byte of content matches.
    for paths in inodes.values():
        if len(paths) > 1:
            primary = sorted(paths)[0]
            for p in paths:
                entries[p]["link_group"] = primary
    return entries


def sha_of_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for c in iter(lambda: f.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


def pack_batches(paths, sizes, budget):
    """Group paths so each batch dumps at most `budget` bytes at once.

    A FIXED COUNT IS THE WRONG UNIT. 400 files is a few megabytes of headers
    or it is four 300 MB binaries; the scratch directory has to hold whichever
    it turns out to be. Packing by bytes makes peak scratch a property of this
    setting and not of what the image happens to contain, so the default is
    safe on a tmpfs without anyone having to think about it. A file larger
    than the budget goes in a batch of its own -- it still has to be dumped
    whole, and pretending otherwise would just move the surprise.
    """
    out, cur, acc = [], [], 0
    for p in paths:
        n = sizes.get(p) or 0
        if cur and acc + n > budget:
            out.append(cur); cur, acc = [], 0
        cur.append(p); acc += n
    if cur:
        out.append(cur)
    return out


def hash_all(img, paths, sizes, scratch, budget, label, quiet):
    """sha256 every named path, dumping and unlinking in batches.

    TWO THINGS HERE EXIST BECAUSE THE FIRST VERSION REPORTED FALSE MATCHES.
    Both were found by planting a same-size edit in /usr/bin/libtool and
    watching the tool call the two images identical.
    
    PATHS ARE QUOTED. `dump /usr/share/cmake-4.2/Help/generator/Borland
    Makefiles.rst /scratch/d7` is four words to debugfs, which errors -- and
    the error DESYNCHRONISES THE REST OF THE BATCH, so dumps after it landed
    empty. 27 paths in this image carry spaces (setuptools and cmake docs),
    which was enough to zero the hashes of everything downstream of them in
    the same chunk. Two empty files hash equal, so the tool reported IDENTICAL
    for files that differ. Quoting is the fix; the verification below is the
    proof it worked.

    EVERY DUMP IS CHECKED AGAINST THE SIZE THE WALK ALREADY READ. A dump that
    produced the wrong number of bytes is retried on its own, and a retry that
    still disagrees is UNREADABLE rather than a hash. Trusting a batched dump
    without checking is exactly how the empty files got through, and an
    unverified hash is worse than no hash because it looks like an answer.
    """
    out = {}
    total = len(paths)
    done = 0
    for chunk in pack_batches(paths, sizes, budget):
        tmp = {p: os.path.join(scratch, "d%d" % n) for n, p in enumerate(chunk)}
        for t in tmp.values():
            if os.path.exists(t):
                os.unlink(t)
        debugfs_batch(img, ['dump "/%s" %s\n' % (p, tmp[p]) for p in chunk])
        for p in chunk:
            t = tmp[p]
            want = sizes.get(p)
            got = os.path.getsize(t) if os.path.exists(t) else None
            if got != want:
                # ONE MORE TRY, ALONE, where no other command can disturb it.
                if os.path.exists(t):
                    os.unlink(t)
                subprocess.run([DEBUGFS, "-R", 'dump "/%s" %s' % (p, t), img],
                               capture_output=True, text=True)
                got = os.path.getsize(t) if os.path.exists(t) else None
            if got != want:
                out[p] = "UNREADABLE(want %s got %s)" % (want, got)
                if os.path.exists(t):
                    os.unlink(t)
                continue
            out[p] = sha_of_file(t)
            os.unlink(t)
        done += len(chunk)
        if not quiet:
            sys.stderr.write("\r  hashing %s: %d/%d" % (label, done, total))
            sys.stderr.flush()
    if not quiet and total:
        sys.stderr.write("\n")
    return out


def describe(e):
    if e is None:
        return "absent"
    if e["kind"] == "l":
        return "symlink -> %s" % e.get("target")
    if e["kind"] == "d":
        return "dir mode %s" % e["mode"]
    return "file %d bytes mode %s" % (e["size"], e["mode"])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image_a")
    ap.add_argument("image_b")
    ap.add_argument("--scratch", help="working directory for dumps (default: a "
                                      "temp dir; removed on exit)")
    ap.add_argument("--budget", type=int, default=64,
                    help="MiB of dumps held at once (default 64); peak scratch "
                         "use is this, or one file if a file is larger")
    ap.add_argument("--quick", action="store_true",
                    help="metadata only -- CANNOT see same-size content changes")
    ap.add_argument("--summary", action="store_true",
                    help="counts and locations only, no per-path detail")
    ap.add_argument("--quiet", action="store_true",
                    help="suppress the hashing progress line")
    a = ap.parse_args()
    summary_only = a.summary

    global DEBUGFS
    DEBUGFS = find_debugfs()
    if not shutil.which(DEBUGFS) and not os.path.exists(DEBUGFS):
        sys.stderr.write("no debugfs found (looked for veron-tools/debugfs and "
                         "the host's; set DEBUGFS= to name one)\n")
        return 2
    print("debugfs: %s" % DEBUGFS)

    print("walking A: %s" % a.image_a)
    ea = walk(a.image_a)
    print("walking B: %s" % a.image_b)
    eb = walk(a.image_b)
    print("  A: %d entries    B: %d entries" % (len(ea), len(eb)))

    ha, hb = {}, {}
    if not a.quick:
        scratch = a.scratch or tempfile.mkdtemp(prefix="imgcmp.")
        os.makedirs(scratch, exist_ok=True)
        fa = sorted(p for p, e in ea.items() if e["kind"] == "f")
        fb = sorted(p for p, e in eb.items() if e["kind"] == "f")
        try:
            budget = a.budget * 1024 * 1024
            sa = {p: e["size"] for p, e in ea.items() if e["kind"] == "f"}
            sb = {p: e["size"] for p, e in eb.items() if e["kind"] == "f"}
            big = max([0] + [v for v in list(sa.values()) + list(sb.values())])
            if not a.quiet:
                print("  hashing %d + %d files, at most %d MiB of scratch at a time"
                      % (len(fa), len(fb), max(a.budget, (big + 1048575) // 1048576)))
            ha = hash_all(a.image_a, fa, sa, scratch, budget, "A", a.quiet)
            hb = hash_all(a.image_b, fb, sb, scratch, budget, "B", a.quiet)
        finally:
            if not a.scratch:
                shutil.rmtree(scratch, ignore_errors=True)

    problems = []
    for p in sorted(set(ea) | set(eb)):
        x, y = ea.get(p), eb.get(p)
        if x is None:
            problems.append(("B-ONLY", p, "absent", describe(y)))
            continue
        if y is None:
            problems.append(("A-ONLY", p, describe(x), "absent"))
            continue
        if x["kind"] != y["kind"]:
            problems.append(("TYPE", p, x["kind"], y["kind"]))
            continue
        if x["mode"] != y["mode"]:
            problems.append(("MODE", p, x["mode"], y["mode"]))
        if (x["uid"], x["gid"]) != (y["uid"], y["gid"]):
            problems.append(("OWNER", p, "%d:%d" % (x["uid"], x["gid"]),
                             "%d:%d" % (y["uid"], y["gid"])))
        if x.get("link_group") != y.get("link_group"):
            problems.append(("HARDLINK-GROUP", p, x.get("link_group", "-"),
                             y.get("link_group", "-")))
        if x["kind"] == "l" and x.get("target") != y.get("target"):
            problems.append(("SYMLINK-TARGET", p, x.get("target"), y.get("target")))
        if x["kind"] == "f":
            # SIZE AND CONTENT ARE SEPARATE ROWS AND A PATH CAN APPEAR UNDER
            # BOTH. Collapsing them would mean this program deciding which
            # difference the reader cares about.
            if x["size"] != y["size"]:
                problems.append(("SIZE", p, str(x["size"]), str(y["size"])))
            if not a.quick and ha.get(p) != hb.get(p):
                problems.append(("CONTENT", p, (ha.get(p) or "?")[:16],
                                 (hb.get(p) or "?")[:16]))

    print()
    if a.quick:
        print("!! --quick: NO CONTENT WAS COMPARED. A file with the same size")
        print("!! and different bytes reads as identical here. Do not use this")
        print("!! result to conclude the two images match.")
        print()
    if not problems:
        print("no metadata differences (CONTENT NOT CHECKED)" if a.quick
              else "IDENTICAL -- every entry, every field, every byte.")
        return 0
    kinds = {}
    for k, p, x, y in problems:
        kinds.setdefault(k, []).append((p, x, y))

    # THE SUMMARY COMES FIRST AND IS PART OF THE OUTPUT.
    #
    # An earlier version printed the detail and left the reader to grep the
    # category headings back out of a 40,000-line file to find out how bad it
    # was. Counting the findings is the tool's job: the first screen answers
    # "how many, of what kind, and where", and everything after it is the
    # evidence for that answer.
    print("NOT IDENTICAL -- %d difference(s) across %d path(s)"
          % (len(problems), len({p for _, p, _, _ in problems})))
    print()
    for k in sorted(kinds, key=lambda k: (-len(kinds[k]), k)):
        print("  %-16s %6d" % (k, len(kinds[k])))
    print()

    # WHERE, WITHOUT READING EVERY LINE. Two directories with 200 differences
    # each is one story; 400 scattered across the tree is a different one, and
    # the counts above cannot tell them apart.
    tops = {}
    for _, p, _, _ in problems:
        tops.setdefault("/".join(p.split("/")[:3]), set()).add(p)
    # EVERY LOCATION, NOT THE TOP FIFTEEN. An earlier version capped this and
    # printed "... and 5 more location(s)", which on a twenty-line list hides
    # a quarter of the answer to save five lines and sends the reader back
    # into the detail to reconstruct what was withheld. The cap was there for
    # no reason; a summary that omits part of the summary is not one.
    print("  differing paths by location (%d):" % len(tops))
    for t, ps in sorted(tops.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        print("    %-52s %5d" % (t, len(ps)))
    print()

    if summary_only:
        print("(--summary: detail suppressed; rerun without it for every path)")
        return 1

    for k in sorted(kinds):
        rows = kinds[k]
        print("\n%s (%d)" % (k, len(rows)))
        for p, x, y in sorted(rows):
            print("  %s" % p)
            print("      A: %s" % x)
            print("      B: %s" % y)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
